### ISSUE TITLE
Docker Compose Vite Error

### ISSUE THREAD

**Issue by SimplyPancake** [Astronautilus14/rially#28]
help
![image](https://github.com/Astronautilus14/rially/assets/24267158/2702ba42-8417-4c07-aad3-914457c77f31)

**Comment by Nierot** [comment]
Oke wat ik denk dat hier is gebeurt is dat je je deps hebt geinstalleerd op de host, en niet in de container. Esbuild is namelijk niet geschreven in JS, maar in Golang. Dit heeft als consequentie dat het alleen maar werkt op het platform waar je het op installeerd. Verwijder je `node_modules` in `frontend` en run vervolgens npm i in je container. Dit kan met `docker exec -it riallynaut-frontend-1 bash` gevolgd door een `npm i`

**Comment by Astronautilus14** [comment]
> Oke wat ik denk dat hier is gebeurt is dat je je deps hebt geinstalleerd op de host, en niet in de container. Esbuild is namelijk niet geschreven in JS, maar in Golang. Dit heeft als consequentie dat het alleen maar werkt op het platform waar je het op installeerd. Verwijder je `node_modules` in `frontend` en run vervolgens npm i in je container. Dit kan met `docker exec -it riallynaut-frontend-1 bash` gevolgd door een `npm i`

of dus gewoon niet de node_modules mounten :p, heb de docker-compose nu herschreven, dus dan moet iemand met windows dit maar even een keer testen

**Comment by Astronautilus14** [comment]
Ik zie het ook nog als fix de frontend niet  als service te runnen maar gewoon appart sinds het toch geen envs gebruikt

**Comment by Nierot** [comment]
het is toch normale svelte? dan boeit het echt niet of het nou wel of niet in docker draait

**Comment by Astronautilus14** [comment]
fixed by not mounting the node_modules
